### ISSUE TITLE
can't install wxmacmolplt in Linux Mint 18 

### ISSUE THREAD

**Issue by davidsousarj** [brettbode/wxmacmolplt#104]
Hi. I recently upgraded my OS to Linux Mint 18 (which is based on Ubuntu 16.04) and tried to install wxmacmolplt but I can't. Before that I was using Linux Mint 17 and the program worked well.

I tried with both ubuntu repositories and building the source code. Maybe it is a problem with the wxwidgets packages but I'm not sure of that.

Firstly I tried with the ubuntu repositories. By the way, it only works if I write like this in the `sources.list` file:

    deb [trusted=yes] https://dl.bintray.com/brettbode/Trusty trusty main 

or

    deb [trusted=yes] https://dl.bintray.com/brettbode/wxMacMolPlt-precise precise

When I try to install wxmacmolplt it says:

    The following packages have unmet dependencies:
    wxmacmolplt : Depends: libwxbase2.8-0 (>= 2.8.12.1) but it is not installable
    Depends: libwxgtk2.8-0 (>= 2.8.12.1) but it is not installable
    E: Unable to correct problems, you have held broken packages.

I've already installed all wxWidgets dependencies, but it keeps saying the same error.
When I try to build wxmacmolplt from source, I get the following error in the `configure` script:

    checking for wxWidgets libraries... not found
    configure: error: have you set LD_LIBRARY_PATH correctly?

I have wxWidgets 3.0.2 correctly installed.

**Comment by brettbode** [comment]
Hmm... That is odd. I thought the those packages were built against wxWidgets 3.0.x. I'll have to check my VM test images tonight.

**Comment by brettbode** [comment]
Tonight I checked my 14.04 system. With the Trusty deb source binary line the 7.7 binary is showing a 3.0 dependency and installs ok there. Can you paste in the output of a "apt-cache show wxmacmolplt" command? I expect there to be three versions available, but the latest (7.7) should list wx 3.0 as the dependency. That said I haven't tested that it works on 16.04, but it should at least have the right dependency.

Your other point was about installing from source. Are you using the OS provided wxWidgets? If so make sure you have the -dev package. Looks like I have libwxbase3.0-dev and libwxgtk3.0-dev.

**Comment by brettbode** [comment]
Hi David,
   I built a 16.04 VM tonight and have resolved the issue. Not sure if my wildcarding is at fault or if I should just point at bad naming in Ubuntu, but apparently the wx package versions in 16.04 have a v5 appended to them and so they don't match the >= 3.0 test even though they obviously are... Safest fix was to build a binary on 16.04 and post that. You can replace your sources line with:
deb [trusted=yes] https://dl.bintray.com/brettbode/Xenial xenial main

Then after updating you should be able to install wxmacmolplt without a problem. Let me know so I can close the issue.

Thanks,
Brett

**Comment by davidsousarj** [comment]
Hi Brett.
Indeed, I was suspecting that the problem was in those "v5" in the package names. Now I can install it correctly with the new source line.

Thank you very much,
David.

**Comment by brettbode** [comment]
Great! It doesn't hurt to have a binary built directly in 16.04 to avoid any subtle incompatibilities.

Thanks,
Brett
