### ISSUE TITLE
Can we get a (fixed) direct download link for Windows binaries?

### ISSUE THREAD

**Issue by teknowledgist** [brettbode/wxmacmolplt#106]
### Please describe the problem or enhancement:
I like the Windows installers because wxMacMolPlt appears in the "Programs and Features", but I'd like to script the download and install for Chemistry classrooms.  With the current Box.com shared file links for the binaries, that is not possible because the file download URL constantly changes.  A user must manually click on the download button to get the files.

Box.com has information on how to get a direct-download link (i.e. click the link and the file is downloaded) here:  https://community.box.com/t5/Collaboration-and-Sharing/Direct-Linking-To-A-File/ta-p/148
However, it does require a paid account with Box.com.  I'm not sure of the account status for this project.

Is there no other means of distributing the Windows binaries that allows for a direct download?

Thanks.

**Comment by teknowledgist** [comment]
BTW, I just tested it, and Dropbox allows for a fixed, direct download for executable files on free accounts too.  Thus, a free, 2GB Dropbox account would allow for all past and current (and many future) versions of the Windows binaries to be directly downloadable.

**Comment by brettbode** [comment]
The issue with the Windows installer links is that box prevents direct links to msi and exe files. Maybe I can zip the file first which is allowed as a direct link.

**Comment by brettbode** [comment]
Ziping the installer does work and allows a direct link, but then you must manually run the installer so I don't know which is better.

**Comment by teknowledgist** [comment]
I'm looking to script this anyway, so download-and-run vs download-unzip-and-run is of little difference.  The sticking point is the download part.

**Comment by brettbode** [comment]
I have created a direct download link for the 64 bit windows installer and added it to the downloads page. The link is https://uofi.box.com/shared/static/k4x3lc5g1x3qhkn7qy3l8ismoj3qd9kd.zip
That said I forgot to ask if you wanted something like a symlink to the current version or if you prefer a new link for each release? Also let me know if you need a similar link for the 32 bit installer.
