### ISSUE TITLE
Energy Plot from .xyz files 

### ISSUE THREAD

**Issue by davidsousarj** [brettbode/wxmacmolplt#111]
I often use wxMacmolplt in order to analyse results from the software Jaguar. It can generate .xyz and .molf files. The .xyz files contains data from geometry optimization: the geometries and energies from every step. wxMacmolplt can read the geometries as different frames, but it isn't able to read the energies, which are in the title lines of each geometry. I wish I could see the energy values from such .xyz file with the option  Subwindow > Energy Plot, which is already implemented in the program.

**Comment by brettbode** [comment]
Hello David,
   I finally got back to adding features to MacMolPlt and have coded up a simple method along the lines you have requested. It will look for a number at the beginning of the label line and set it to the energy. This is for XMol style XYZ files. There was already an undocumented way of doing the same for MolDen format files. At one point it was common for the label line in those files to have "scf done:" followed by an energy so the code already looks for "done:" and reads what follows as the energy. The new code and updated documentation will be in the next release. Let me know if you would like to try it before then.

**Comment by davidsousarj** [comment]
Thanks, @brettbode !

I'm nowadays working with VB2000 in GAMESS. VB2000 generates *.xyz files for reaction path runs. In the label lines there is something line "reactor run - point number N     Energy E" where N is the point and E is the energy. Is it possible to read the energy in such files also?

**Comment by davidsousarj** [comment]
Here is an example file.x'
[exam-vb10-full.xyz.txt](https://github.com/brettbode/wxmacmolplt/files/7153785/exam-vb10-full.xyz.txt)

**Comment by brettbode** [comment]
Hi David,
   That is easy enough to accomplish. I have checked in code that will parse "Energy = " out of the title line of each geometry and set it to the energy. It is in the repo now. If you would like a binary let me know.

**Comment by davidsousarj** [comment]
Hi, Brett. Thank you very much! It would be very helpful to send me a binary. I'm using 64-bit Ubuntu 20.04.

**Comment by davidsousarj** [comment]
I have managed to download the repo, build and test it here. But it seems it is not working properly. Here is what I got with the example file I have sent you:

![image](https://user-images.githubusercontent.com/5395575/134694582-19a82389-43cd-4b66-ae7f-693b7fbfa69c.png)

**Comment by brettbode** [comment]
Hi David,
   Good catch! I did not think about there not being anything to key the x-coordinate off of previously for XYZ files. I have added code that will just use the geometry number which is probably sufficient for most purposes.

**Comment by davidsousarj** [comment]
Excelent! I think the issue can be closed now.

**Comment by brettbode** [comment]
Great! I am working on finishing up an issue and then will push a new release so the current repo is pretty much version 7.7.2.

Thanks!
