### ISSUE TITLE
mpGLCanvas.cpp:481: mismatched new and delete ?

### ISSUE THREAD

**Issue by dcb314** [brettbode/wxmacmolplt#122]
I just tried to compile the package with clang. It said:

mpGLCanvas.cpp:481:19: warning: 'void operator delete [](void*)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]

Source code is

        pixels = (GLbyte *)malloc(canvasWidth * canvasHeight * 3 * sizeof(GLbyte));

       delete [] pixels;

**Comment by brettbode** [comment]
Hello,
   Thanks for flagging the bug. I have checked in a change that uses new instead of the malloc which should correct the bug.
