### ISSUE TITLE
wxmacmolplt_7.7.1-1_amd64 & Linux Mint 20.2 Cinnamon

### ISSUE THREAD

**Issue by VictorCiornea** [brettbode/wxmacmolplt#136]
Hello,
Help me install wxmacmolplt (file/version ”wxmacmolplt_7.7.1-1_amd64.deb). I always get this warning (see image attached to message).
I'm using Linux Mint 20.2 Cinnamon 64 bit OS. I seem to be using a version of wxWidgets provided by my operating system vendor, libwxbase3.0-0v5, version 3.0.5.1+dsfg-2.
Thanks in advance for your help.
Respectfully,
Victor

![wxmacmolplt](https://user-images.githubusercontent.com/91259617/134497638-96f86955-548d-44b4-b183-974ef447091a.png)

**Comment by brettbode** [comment]
Hi Victor,
   I am not sure what is going on there. It looks like there is some issue with determining that 3.0.5 is > 3.0.2. I will build a VM using Linux Mint and give it a try myself but that probably won't happen until this weekend.

**Comment by brettbode** [comment]
Hi Victor,
   I see that there were some naming changes to packages in Debian Buster. I was ready to release version 7.7.2 anyway and have created binary .deb files for several versions that should help you. If you have version 3.0.5 of wx then the .deb file for Debian 11 should work, otherwise the .deb file for buster should work against 3.0.4.

**Comment by VictorCiornea** [comment]
> Hi Victor,
> I see that there were some naming changes to packages in Debian Buster. I was ready to release version 7.7.2 anyway and have created binary .deb files for several versions that should help you. If you have version 3.0.5 of wx then the .deb file for Debian 11 should work, otherwise the .deb file for buster should work against 3.0.4.

Thanks for the quick help. I wish you a successful week. Good luck!
