### ISSUE TITLE
Axis of molecule formation not occupying complete screen(Just at corner 1/4 of the screen)

### ISSUE THREAD

**Issue by ghost** [brettbode/wxmacmolplt#138]

**Comment by ProgrammrAnurag** [comment]
The axis In which the molecules are to be drawn, is just occupying 1/4th of the screen in the bottom left corner.
MacMolPLt version 7.7.1
MacOS M1

**Comment by brettbode** [comment]
I believe this issue is now resolved with the latest v7.7.3 release.
