### ISSUE TITLE
no version 7.7.3 release or tag

### ISSUE THREAD

**Issue by rathann** [brettbode/wxmacmolplt#150]
### Please describe the problem or enhancement:

Version 7.7.3 is mentioned on the [website](https://brettbode.github.io/wxmacmolplt/) and available for [download](https://brettbode.github.io/wxmacmolplt/downloads.html), but it's not [tagged](https://github.com/brettbode/wxmacmolplt/tags) in git or listed on GitHub [releases](https://github.com/brettbode/wxmacmolplt/releases) tab. Please add it to GitHub [releases](https://github.com/brettbode/wxmacmolplt/releases) or at least tag it as `v7.7.3`, so that an auto-generated tarball becomes available from GitHub.

**Comment by brettbode** [comment]
Hi,
   I just took care of the tag and release. Sorry for the delay, I am back on the day job so limited amount of time to work on this.
Brett
