### ISSUE TITLE
Help! Compiling issue on OpenSUSE 13.2

### ISSUE THREAD

**Issue by lirfana** [brettbode/wxmacmolplt#60]
Hi, I am a new fan of Linux and I need wxmacmolplt for my reseach. 
Anyway I've been trying to ````make```` wxmacmolplt on my Laptop and I always got this error
````
linux-zyen:/usr/local/wxmacmolplt-7.6 # make
Making all in src
make[1]: Entering directory '/usr/local/wxmacmolplt-7.6/src'
g++ -DPACKAGE_NAME=\"wxmacmolplt\" -DPACKAGE_TARNAME=\"wxmacmolplt\" -DPACKAGE_VERSION=\"7.6\" -DPACKAGE_STRING=\"wxmacmolplt\ 7.6\" -DPACKAGE_BUGREPORT=\"MMP.Guy@gmail.com\" -DPACKAGE_URL=\"\
" -DPACKAGE=\"wxmacmolplt\" -DVERSION=\"7.6\" -I.
 -I/usr/lib/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXGTK__ -pthread -DI
NSTALL_PREFIX=\"NONE\" -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
main.cpp: In member function ‘virtual bool MpApp::OnInit()’:
main.cpp:143:69: error: invalid cast from type ‘wxString’ to type ‘const wxChar* {aka const wchar_t*}’
wxT("Version %s, %s"), wxMacMolPlt_VERSION, (const wxChar*) date);
^
main.cpp: In member function ‘virtual bool MpAppNoGUI::OnInit()’:
main.cpp:533:69: error: invalid cast from type ‘wxString’ to type ‘const wxChar* {aka const wchar_t*}’
wxT("Version %s, %s"), wxMacMolPlt_VERSION, (const wxChar*) date);
^
Makefile:433: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
make[1]: Leaving directory '/usr/local/wxmacmolplt-7.6/src'
Makefile:456: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
````

And this is my ````./configure```` results
````
linux-zyen:/home/LIF # cd /usr/local/wxmacmolplt-7.6
linux-zyen:/usr/local/wxmacmolplt-7.6 # ./configure
configure: loading site script /usr/share/site/i686-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for Ming_init in -lming... no
checking for glewInit in -lGLEW... no
./configure: line 3701: test: =: unary operator expected
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking wxWidgets version... 3.0.2
checking for wxWidgets libraries... yes
checking for OpenGL support in wxWidgets... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
````
Thank you very much for your attention... Cheers!

**Comment by brettbode** [comment]
Hello,
   Did you build wxWidgets from source or install a prebuilt binary package? If from source can you send me the configure line you used for wxWidgets? 

Thanks,
Brett

**Comment by lirfana** [comment]
Hi Brett,
Sorry for the delay. I installed a prebuilt binary package wxGTK3-3_0-devel (3.0.2-2.4.1-i586) and everything that it depends on automatically through YaST2. 

Thanks for the response by the way.
Luth

**Comment by brettbode** [comment]
Hmm... ok I will need to build a VM with OpenSLES 13.2 to try this out and diagnose the issue. I'm not sure that will get done this weekend, but hopefully I can diagnose the issue next week.

**Comment by lirfana** [comment]
Ok Brett.

Thank you very much. I'm looking forward to it.

**Comment by brettbode** [comment]
Hello,
   I have the build issue worked around, though not fully understood. The actually lines it is complaining about are not very important anyway. There are two lines (133 and 532) of the form:
        msg.Printf(wxT("wxMacMolPlt, (c) Iowa State University, 2008-2012 ")
                       wxT("Version %s, %s"), wxMacMolPlt_VERSION, (const wxChar*) date);
Just change that line to drop the (const wChar *) bit so it looks like:
        msg.Printf(wxT("wxMacMolPlt, (c) Iowa State University, 2008-2012 ")
                       wxT("Version %s, %s"), wxMacMolPlt_VERSION, date);

Then it should build fine. Alternatively I went ahead and built a binary RPM for OpenSuse 13.2 (x86_64) that you can grab from:
https://bintray.com/artifact/download/brettbode/generic/wxmacmolplt-7.6-1.opensuse13.2.x86_64.rpm

Best,
Brett

**Comment by lirfana** [comment]
Thank you very much Brett.

Your first solution works like a charm. Now I have successfully make, install, and run wxmacmolplt app on my laptop.

I haven't checked the rpm yet. But I'll save it for my desktop machine at my lab.

And thank you for the lesson.

Best regards.
L

**Comment by lirfana** [comment]
Hi Brett,

I'm sorry if it is not a wxmacmolplt problem. But I think I'm having a
similar wxwidget 3.0.2 compatibility issue on gamessq source code. There
are problems like the use of "wxDIALOG_MODAL" style which is not supported
any longer on the present wxwidget on several source codes. I've been
trying to work around it myself (like removing all wxDIALOG_MODAL style
declaration on some source codes) but I don't think I'm qualified yet to do
this because it just resulting a lot more new error on the compiling step.
Would you be so kind to point me to a right direction.

I'm sorry if this question is a bit random. I don't know where else to ask
because I can't find any Github site or anything else for gamessq except
for the gamessq page on gamess site.

Thank you,
L

2015-07-07 2:34 GMT+07:00 Brett Bode <notifications@github.com>:

> Hello,
> I have the build issue worked around, though not fully understood. The
> actually lines it is complaining about are not very important anyway. There
> are two lines (133 and 532) of the form:
> msg.Printf(wxT("wxMacMolPlt, (c) Iowa State University, 2008-2012 ")
> wxT("Version %s, %s"), wxMacMolPlt_VERSION, (const wxChar*) date);
> Just change that line to drop the (const wChar *) bit so it looks like:
> msg.Printf(wxT("wxMacMolPlt, (c) Iowa State University, 2008-2012 ")
> wxT("Version %s, %s"), wxMacMolPlt_VERSION, date);
>
> Then it should build fine. Alternatively I went ahead and built a binary
> RPM for OpenSuse 13.2 (x86_64) that you can grab from:
>
> https://bintray.com/artifact/download/brettbode/generic/wxmacmolplt-7.6-1.opensuse13.2.x86_64.rpm
>
> Best,
> Brett
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettbode/wxmacmolplt/issues/60#issuecomment-118971782>
> .
>



-- 
Your sincerely,
Luthfan

**Comment by brettbode** [comment]
Hi,
   I guess that doesn’t surprise me too much. I have not spent time on GQueue for quite some time so haven’t updated the code to build against the latest wxWidgets. I will see what I can do this weekend.

Best,
Brett

> On Jul 9, 2015, at 11:40 PM, lirfana <notifications@github.com> wrote:
> 
> Hi Brett,
> 
> I'm sorry if it is not a wxmacmolplt problem. But I think I'm having a
> similar wxwidget 3.0.2 compatibility issue on gamessq source code. There
> are problems like the use of "wxDIALOG_MODAL" style which is not supported
> any longer on the present wxwidget on several source codes. I've been
> trying to work around it myself (like removing all wxDIALOG_MODAL style
> declaration on some source codes) but I don't think I'm qualified yet to do
> this because it just resulting a lot more new error on the compiling step.
> Would you be so kind to point me to a right direction.
> 
> I'm sorry if this question is a bit random. I don't know where else to ask
> because I can't find any Github site or anything else for gamessq except
> for the gamessq page on gamess site.
> 
> Thank you,
> L
> 
> 2015-07-07 2:34 GMT+07:00 Brett Bode <notifications@github.com>:
> 
> > Hello,
> > I have the build issue worked around, though not fully understood. The
> > actually lines it is complaining about are not very important anyway. There
> > are two lines (133 and 532) of the form:
> > msg.Printf(wxT("wxMacMolPlt, (c) Iowa State University, 2008-2012 ")
> > wxT("Version %s, %s"), wxMacMolPlt_VERSION, (const wxChar*) date);
> > Just change that line to drop the (const wChar *) bit so it looks like:
> > msg.Printf(wxT("wxMacMolPlt, (c) Iowa State University, 2008-2012 ")
> > wxT("Version %s, %s"), wxMacMolPlt_VERSION, date);
> >
> > Then it should build fine. Alternatively I went ahead and built a binary
> > RPM for OpenSuse 13.2 (x86_64) that you can grab from:
> >
> > https://bintray.com/artifact/download/brettbode/generic/wxmacmolplt-7.6-1.opensuse13.2.x86_64.rpm
> >
> > Best,
> > Brett
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/brettbode/wxmacmolplt/issues/60#issuecomment-118971782>
> > .
> >
> 
> 
> 
> -- 
> Your sincerely,
> Luthfan
> —
> Reply to this email directly or view it on GitHub.
> 

Brett Bode
Primary developer of MacMolPlt
MMP.Guy@gmail.com

**Comment by brettbode** [comment]
Hi,
   I have gotten GamessQ building and running against the latest wxWidgets and on OpenSuse 13.2. I have done only basic testing, but it seems to be functioning now. I haven't posted it to the usual site, but have a link for you to try:
https://uofi.box.com/s/xcdkplog6ekucqdjcn10gj58fdhyrjt5
I also have current gms and rungms scripts that you might also find useful:
https://uofi.box.com/s/nanqhq13kvaybfneourr6ift4jbxtdmq
https://uofi.box.com/s/y1ymkd10w8jp2eqg08xcpmpyusesg28v

You should be able to configure, make, make install and be ready to go.

Best,
Brett

**Comment by lirfana** [comment]
Hi Brett,

Thank you very much for the BIG help. They are all working gracefully on my
machine.
Now I can enjoy having fun computations in my lab or at home.
I've been tasked by my Head of Division to kick start a computational
research group at my Department. A lot of hard work ahead.
I know we have been decades behind, but we are willing to catch up.

Thank you once again for the valuable lessons, it has been a fun ride
getting to know Linux.
I hope you wouldn't mind if I asked you another questions in the future.

Best regards,
L


2015-07-12 22:41 GMT+07:00 Brett Bode <notifications@github.com>:

> Hi,
> I have gotten GamessQ building and running against the latest wxWidgets
> and on OpenSuse 13.2. I have done only basic testing, but it seems to be
> functioning now. I haven't posted it to the usual site, but have a link for
> you to try:
> https://uofi.box.com/s/xcdkplog6ekucqdjcn10gj58fdhyrjt5
> I also have current gms and rungms scripts that you might also find useful:
> https://uofi.box.com/s/nanqhq13kvaybfneourr6ift4jbxtdmq
> https://uofi.box.com/s/y1ymkd10w8jp2eqg08xcpmpyusesg28v
>
> You should be able to configure, make, make install and be ready to go.
>
> Best,
> Brett
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettbode/wxmacmolplt/issues/60#issuecomment-120731338>
> .
>



-- 
Your sincerely,
Luthfan

**Comment by brettbode** [comment]
Not a problem. GamessQ was long over due for an update. I believe I have it working properly again on Max OS X and Linux so will probably push out a release for those soon. If you do run into further issues with it feel free to file another ticket, though note that I created a separate GitHub project for GamessQ over the weekend so you can file new issues for it under that project.

Best,
Brett
