### ISSUE TITLE
Crash when Subwindow>Surfaces>3D Orbital attempts to update

### ISSUE THREAD

**Issue by Daniel-ONeill** [brettbode/wxmacmolplt#81]
Hello!

I am hoping someone might be able to help! I am trying to model some materials in GAMESS and need to get the orbitals out in MacMolPlt. To do this I've always previously gone Subwindow>Surfaces>3D Orbital, picked an energy level and then clicked update. It then draws that energy level's orbital. I had always done this on a Windows XP computer that I no longer have access to. I am now trying to do the same thing but when I click Update it crashes every time! Here is a list of the things I have tried:

- Run in both Ubuntu and XP
- Made sure wxWidgets and wxMacMolPlt are up to date
- Tried a file I know works

Not really sure what to try/how to fix it? I can't find any other of the same issues online anywhere... I have included a paste bin to an example .log file that exhibits the above behaviour. http://pastebin.com/Vgxn045y 

Any help?

Thanks!

**Comment by brettbode** [comment]
Hi Daniel,
   I believe this is a bug I already fixed and checked in, but haven't pushed out in a release. Are you building from source or a prebuilt binary?

Thanks,
Brett

**Comment by Daniel-ONeill** [comment]
Hi Brett


I am using a prebuilt library


Thanks

Dan

________________________________

**Comment by brettbode** [comment]
Dan,
   I built a 32 bit binary that I believe will install and run on XP and posted it at:
https://uofi.box.com/shared/static/86vgyvygz73qb0bgfxj0vnr4kbug2tpo.msi

I forgot to ask the version of Ubuntu and whether it is 32 or 64 bit?

Brett

**Comment by brettbode** [comment]
Hi Daniel,
   I completed a new release (7.6.2) that includes the fix for the issue you reported. The source and binaries are available from the usual site.

Brett
