### ISSUE TITLE
Firefly compatibility: Reading vib. properties from Hessian calculation is broken

### ISSUE THREAD

**Issue by catox0** [brettbode/wxmacmolplt#97]
### Please describe the problem or enhancement:
When reading vibrational properties from the new Gamess Firefly versions, wxmacmolplt duplicates entries for some vibrational states and fails to read the entries for all states.
This seems to be due to an additional space padding before the newline characterin the vibrational state list:
Old PCGamess: Two spaces after last frequency line 4 (and none in all other lines).
------------------
     FREQUENCIES IN CM**-1, IR INTENSITIES IN DEBYE**2/AMU-ANGSTROM**2

                          1           2           3           4           5
       FREQUENCY:        12.89       12.25       11.56        1.85        2.39  
-----------------
New Gamess Firefly: Three spaces after last frequency in line 4 leads to duplicate reading of the 5th vibrational properties. (The new Firefly also pads all other lines with one space before the newline.)
-----------------
     FREQUENCIES IN CM**-1, IR INTENSITIES IN DEBYE**2/AMU-ANGSTROM**2 

                          1           2           3           4           5 
       FREQUENCY:        12.88       12.26       11.56        1.83        2.39   
----------------
All vibrational states at the end of their line are read twice. The last states are not read.

### If this is a bug report please list the steps required to reproduce the problem:
Run Hessian calculation in Gamess Firefly version 811. Make sure there are a minimum of 6 degrees of freedom for vib/rot/translational motion.
Read output file with wxmacmolplt.

### What version are you running?
WxMacMolPlt 7.5

### What OS are you using? (please include 32/64 bit and if Linux the specific distribution)
Windows 10, 64-bit

**Comment by brettbode** [comment]
Hello,
   I will confirm that regular GAMESS output is parsed correctly and see if there is something I can do to make it flexible, but I do not directly support FireFly since it is an unauthorized fork of GAMESS.

Brett

**Comment by brettbode** [comment]
I improved the flexibility of the parser such that I don't think spaces at the end of the line should matter anymore. Released in v7.7.
